name: Build & Release Native AOT

on:
  push:
    tags:
      - 'v*'  # Matches v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build using Docker and publish to GitHub Releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build --platform=linux/amd64 -t ipmerge-builder -f ipmerge/Dockerfile ipmerge

      - name: Extract built binary from container
        run: |
          docker create --name ipmerge-temp ipmerge-builder
          docker cp ipmerge-temp:/app/out/ipmerge ./ipmerge-linux-x64
          docker rm ipmerge-temp

      - name: Upload binary to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ./ipmerge-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
