name: Build & Release Native AOT

on:
  push:
    tags:
      - 'v*'  # Matches v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build-linux-aot:
    name: Build Linux x64 AOT binary
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y clang lld zlib1g-dev gcc libpthread-stubs0-dev

      - name: Publish Native AOT
        run: |
          dotnet publish -c Release -r linux-x64 \
            -p:PublishAot=true \
            -p:SelfContained=true \
            -p:IlcUseLld=true \
            -p:IlcUseLLVM=true \
            -o ./publish

      - name: Rename binary for release
        run: mv ./publish/ipmerge ./ipmerge-linux-x64

      - name: Upload Release binary
        uses: softprops/action-gh-release@v2
        with:
          files: ./ipmerge-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
